languageCode = 'en-us'
baseUrl = 'https://jason.schwarzenberger.co.nz/'
title = 'Jason Schwarzenberger'
theme = 'anubis'
paginate = 10.0
disqusShortname = ''
googleAnalytics = ''
[[menu.main]]
identifier = 'posts'
name = 'Archive'
title = 'Archive'
url = '/posts/'
weight = 1.0

[[menu.main]]
identifier = 'tags'
name = 'Tags'
title = 'Tags'
url = '/tags/'
weight = 2.0

[params]
author = 'Jason'
description = 'Software engineer from New Zealand.'
images = ['images/Schwarzenberger.png']
customCSS = ['css/my.css']
dateFormat = '2006-01-02 15:04'
