languageCode = 'en-us'
x_baseUrl = 'https://jason.schwarzenberger.co.nz/'
title = 'Jason Schwarzenberger'
theme = '1jnz'
paginate = 10.0

[[menu.main]]
identifier = 'posts'
name = 'Archive'
title = 'Archive'
url = '/posts/'
weight = 1.0

[[menu.main]]
identifier = 'tags'
name = 'Tags'
title = 'Tags'
url = '/tags/'
weight = 2.0

[params]
author = 'Jason'
description = 'Senior Front-end Engineer'
images = ['/images/Schwarzenberger.png']
favicon = 'favicon.ico'
customCSS = ['css/my.css']

    [params.theme_config]
    appearance        = "auto"
    back_home_text    = "back"
    date_format       = '2006-01-02 15:04'
    isListGroupByDate = false
    isShowFooter      = false


    [params.profile]
    name = 'Jason Schwarzenberger'
    label = 'Senior Front-end Engineer'
    email = 'jason@master5o1.com'
    picture = '/images/Schwarzenberger.png'

        [[params.profile.social]]
        name = 'github:jason-s13r'
        url = 'https://github.com/jason-s13r'

        [[params.profile.social]]
        name = 'guestbook.1j.nz'
        url = 'https://guestbook.1j.nz'

        [params.profile.location]
        city = 'Whangārei'
        country = 'New Zealand'
        countryCode = 'NZ'

        [params.profile.webring]
        label = 'Webring:'

        [[params.profile.webring.entry]]
        label = 'Previous'
        url = 'https://remycoppard.xyz'

        [[params.profile.webring.entry]]
        label = 'Index'
        url = 'https://webring.t0.vc'
        
        [[params.profile.webring.entry]]
        label = 'Next'
        url = 'https://elefantlover.github.io/'